name: 15-1-self-hosted-runner
on: 
    workflow_dispatch: 
jobs:
    verify-runner:
        name: Verify Self-Hosted Runner
        runs-on: gcp # any runner can be picked
        #runs-on: [ self-hosted, gcp, ubuntu] # and condition
        steps:
        - name: Print Runner Information
          run: |
            echo "==================================="
            echo "SELF-HOSTED RUNNER INFORMATION"
            echo "==================================="
            echo "Runner OS     :   ${{ runner.os }}"
            echo "Hostname      :   $(hostname)"
            echo "User          :   $(whoami)"
            echo "Working dir   :   $(pwd)"
            echo "Ip address    :   $(hostname -i)"
        - name: Check Installed tools
          run: |
            echo "==================================="
            echo "INSTALLED TOOLS"
            echo "==================================="
            echo "Java      : $(java -version 2>&1 | head -1)"
            echo "Docker    : $(docker --version)"
            echo "Maven     : $(mvn --version 2>&1 | head -1)"



# self-hosted,linux,gcp