name: 05-github-env
on: 
  workflow_dispatch:
jobs:
    githu-env-demo:
      runs-on: ubuntu-latest
      steps:
      - name: Set Variables
        run: |
          echo "APP_VERSION=1.0.0" >> $GITHUB_ENV
          echo "NAME=Siva" >> $GITHUB_ENV
          echo "Trying to Print APP_VERSION and NAME in the same step"
          echo "Application Version is: $APP_VERSION"
          echo "Name is: $NAME"
      - name: Print Variables
        run: |
          echo "Trying to Print APP_VERSION and NAME in the next step"
          echo "Application Version is: $APP_VERSION"
          echo "Name is: $NAME"
# First Step: APP_VERSION and NAME print nothing 
# second step APP_VERSION and NAME are printing correctly.,
# $GITHUB_ENV is a special file that allows you to set environment variables that will be available to all subsequent steps in the workflow.
# $GITHUB_ENV  variable are only availble in the same job.