# success 
# failure 
# always
# cancelled 
name: Status Check Function Demo 
on: 
    workflow_dispatch: 
jobs:
    status-demo:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Build 
              run: |
                echo "Building the application....."
                exit 1 
            - name: Step 2 - Success 
              if: ${{ success() }}
              run: echo "Previous Steps are succesful"
            - name: Step 3 - Failure
              if: ${{ failure()}}
              run: echo "Previous Steps has failed"
            - name: Step 4 - always
              if: ${{ always()}}
              run: echo "I will run irrespective of success or failure"
            - name: Step 5 - Cancelled
              if: ${{ cancelled()}}
              run: echo "Workflow was cancelled"
