name: workflow-1
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Name
        run: |
          echo "Actor is : ${{ github.actor }}"
          echo "Commit SHA is:        ${{ github.sha }}"
      - name: Step 2
        run: |
          echo "Intentionally Failing this step"
          exit 1