name: java-build-custom-actions

inputs:
  java-version:
    description: selecting java version
    required: false
    default: '21'

  distribution:
    description: selecting java distribution
    required: false
    default: 'temurin'

  run-tests:
    description: selecting tests to run or not
    required: false
    default: 'true'

  working-directory:
    decription: selecting work directory
    required: false
    default: '.'

outputs:
  test-result: 
    value: ${{steps.test.outputs.result}}
  build-result:
    value: ${{steps.build.outputs.result}}

runs:
  using: composite
  steps:
    - name: setup-java
      uses: actions/setup-java@v5
      with:
        java-version: ${{inputs.java-version}}
        distribution: ${{inputs.distribution}}

    - name: running tests
      id: test
      if: ${{inputs.run-tests == 'true'}}
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        mvn test
        echo "result= Tests are completed successfully!" >> $GITHUB_OUTPUT

    - name: Skipped Tests
      if: ${{inputs.run-tests != 'true'}}
      run: |
        echo "result= Tests are Skipped successfully!" >> $GITHUB_OUTPUT

    - name: maven build
      id: build
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        mvn clean package -DskipTests
        echo "result= Build is completed successfully!" >>GITHUB_OUTPUT
      