name: CI_Project_5.0
on:
  push:
    branches:
      - master
    paths:
      - "src/**"
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - 'pom.xml'
jobs:
  test-job:
    name: Codechekout and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Code-checkout
        uses: actions/checkout@v4

      - name: Java-Setup
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: To check java version
        run: java --version

      - name: maven testing
        run: mvn test

      - name: uploading test results
        uses: actions/upload-artifact@v4
        with:
          name: test results madhav
          path: target/surefire-reports/
          if-no-files-found: error
          retention-days: 30
