name: Simple-CI-pipeline
on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "Dockerfile"
      - "pom.xml"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "Dockerfile"
      - "pom.xml"
      - ".github/**"
  workflow_dispatch:
jobs:
  all-in-one:
    name: code,javaSetup, build, upload
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v4

      - name: setup-build-environment
        uses: actions/setup-java@v5
        with: 
          distribution: temurin
          java-version: '21'

      - name: build-code
        run: mvn clean package

      - name: upload-artifactory
        uses: actions/upload-artifact@v4
        with:
          name: generate jar artifacgory uploading..
          path: target/*.jar
          retention-days: 30   
      - name: listing the files
        run: |
          pwd
          ls -ltr 