name: 6.0.2-GITHUB_ENV-variable
on: 
  workflow_dispatch:
jobs:
  job1:
    steps:  
      - name: step1
        run: |
          echo "APP=Swiggy" >> $GITHUB_ENV
          echo "ENVIRONMENT=TEST" >>GITHUB_ENV
          echo "printing application name: $APP"

      - name: step2 
        run: |
          echo "Application is: $APP"
          echo "Environment deployed is: $ENVIRONMENT"

      - name: step3 repo varaibales and secrets
        run: |
          echo "Username is: ${{vars.user}}"
          echo "password is: ${{secrets.pw}}"



