name: CI-Promotion-file
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target Environment
        type: choice
        options:
          - production
          - staging
          - dev
      version:
        description: Version to Deploy?
        type: string
        default: v1.0.0
  push:
    branches:
      - master
    paths:
      - "Dockerfile"
      - "pom.xml"
      - "src/**"
env:
  image_name: madhav2026/i27-dashboard-app

jobs:
  job1:
    name: Code checkout, Build, Artifact, CommitTag
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{steps.tag1.outputs.value}}
    steps:
      - name: code-checkout
        uses: actions/checkout@v5

      - name: setup-java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      
      - name: maven build
        run: mvn clean package

      - name: upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: myjarfile
          path: target/*.jar

      - name: creating image tag
        id: tag1
        run: echo "value=${{github.sha}}" >> $GITHUB_OUTPUT

  job2:
    name: Get code, Docker Build, login, Push
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: checkout-code
        uses: actions/checkout@v5

      - name: Docker Build
        run: docker build -t ${{env.image_name}}:${{needs.job1.outputs.image_tag}} .
      
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{vars.docker_username}}
          password: ${{secrets.docker_password}}

      - name: Docker Push
        run: docker push ${{env.image_name}}:${{needs.job1.outputs.image_tag}}

      - name: Docker Summary
        run: |
          echo "Docker image name is: ${{env.image_name}}:${{needs.job1.outputs.image_tag}}"

  job3:
    if: ${{inputs.environment == 'dev'}}
    name: dev environment
    runs-on: ubuntu-latest
    needs: [job1, job2]
    environment:
      name: dev
      url: http://mydev.usaa.com
    steps:
      - name: Deploying on dev
        run: |
          echo "Dev deployment is completed successfully!"
  job4:
    if: ${{inputs.environment == 'staging'}}
    name: stage environment
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    environment:
      name: staging
      url: http://mystage.usaa.com
    steps:
      - name: Deploying on stage
        run: |
          echo "stage deployment is completed successfully!"

  job5:
    if: ${{inputs.environment == 'production'}}
    name: prod environment
    runs-on: ubuntu-latest
    needs: [job1, job2, job3, job4]
    environment:
      name: production
      url: http://mydprod.usaa.com
    steps:
      - name: Deploying on prod 
        run: |
          echo "prod deployment is completed successfully!"


          